= Raspberry PI unofficial Yocto Project BSP by KOAN

This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. 
In case of sharing please indicate the origin: (C)2020 KOAN - <https://koansoftware.com>

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir yocto-rpi3-zeus
$: cd yocto-rpi3-zeus
$: repo init -u https://github.com/koansoftware/acme-cm3-bsp-platform -b zeus
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To start a simple image build:

[source,console]
$: source sources/poky/oe-init-build-env build
$: bitbake core-image-minimal

You can use any directory to host your build.


== Contributing

To contribute to this layer you should send the patches for review to: info [AT] koansoftware.com

